model:
    modelname: 'unet'
    backbone: 'efficientnet-b0' # 'timm-mobilenetv3_large_100' # 'se_resnext50_32x4d' # 'mobilenet_v2' # 'se_resnext50_32x4d' #'efficientnet-b0' 
    encoder_weights: 'imagenet'
    loss: 'lovasz'
    learning_rate: 0.0001 
    learning_rate_schedule: 'plateau'
sampler:
    training:
        iterations: 1250
        label_dist:
            1: 1.0
            2: 2.0
            3: 5.0
        label_map:
            1: 0
            2: 1 
            3: 2
        patch_shapes:
            1.0: [512, 512]
        mask_spacing: 2.0
        sampler_count: 999
        label_mode: 'load'
    validation:
        seed: 42
        iterations: 1250
        label_dist:
            1: 1.0
            2: 2.0
            3: 5.0
        label_map:
            1: 0
            2: 1 
            3: 2
        patch_shapes:
            1.0: [512, 512]
        mask_spacing: 2.0
        sampler_count: 999
        label_mode: 'load'
training:
    training_batch_size: 10
    validation_batch_size: 10
    epochs: 100
    stop_plateau: 50
    lr_plateau: 15
    lr_reduction_factor: 0.5
    workers: 8
    mixed_precision: true
